:milestone 2 components and redux store
Cyrus-Kiprop/bookstore-react-redux pull request #4
Opened 2020-08-18 17:23 UTC by firmoholanda

in this pr, we implemented the folowing:

- prepare the directory structure using: components, containers, actions and reducers;
- implement the App component with BooksList and BooksForm;
- implement the BooksList component;
- implement the Book component;
- implement the BooksForm component;
- define the Redux actions and reducers
- initialize the Redux store.

2020-08-18 22:05 UTC, bellom requested changes
## Hi Team :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
**Please don't us move away from the instructions stated in the pathwright, know that all students are bind to make use of the project requirements.**

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-08-18 22:05 UTC, bellom commented on src/components/BooksList.js
> +import React from 'react';
This file should also be in `src/container` dir

2020-08-18 22:05 UTC, bellom commented on src/components/BooksList.js
> +
We need to connect to the redux store and fetch the books using `mapStateToProps`
![image](https://user-images.githubusercontent.com/31897434/90569617-19afe500-e1a6-11ea-80a0-abc242cbe244.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896827/

2020-08-18 22:05 UTC, bellom commented on src/containers/App.js
> +import React from 'react';
we need to re-arrange some files.
let's work on the file dir.
![image](https://user-images.githubusercontent.com/31897434/90569782-5e3b8080-e1a6-11ea-8f4c-58d7c3fea8f2.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896827/

2020-08-19 10:24 UTC, Cyrus-Kiprop commented
### Thanks for your wonderful review @bellom. I have implemented the requested changes in the updated pull request. They include;
- Hook BooksList component into the redux store with the help of mapStateToProps.
- Update the contents of components and container directory.

2020-08-19 11:25 UTC, Oghenebrume50 approved these changes
### APPROVED

Hi @firmoholanda @Cyrus-Kiprop awesome job team, this looks good to me, please move on to the next milestone

**This is approved** :+1: 

**RAPHAEL NORIODE** :mask: STAY_SAFE

2020-08-19 12:12 UTC, merged