pr for microverse tse approval: milestone 4 category filter
Cyrus-Kiprop/bookstore-react-redux pull request #8
Opened 2020-08-19 18:38 UTC by firmoholanda

in this pr, we implemented the folowing:

- create the CHANGE_FILTER action in actions/index.js;
- create a filter.js;
- implement the CategoryFilter component;
- render the CategoryFilter component in the BooksList component;
- implement the handleFilterChange;
- implement a conditional method which decides which books should be shown in the table;

2020-08-20 22:25 UTC, Forison requested changes
## Status:: Change Required❌.

# 🙋‍♂️ Holanda & Kiprop. 

#### You have done a great job on this one. All the requirements were almost met, however, there is an issue to address🤗.

* [ ] It’s better to delete commented piece of codes. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

### That is it, kindly make the change and submit a re-review😎.

#### Happy coding👨‍💻

Addo Forison

2020-08-20 22:25 UTC, Forison commented on src/components/CategoryFilter.js
> +  // const handleFilterChange = (event) => {
- Kindly remove the commented code

2020-08-21 15:42 UTC, firmoholanda commented on src/components/CategoryFilter.js
> +  // const handleFilterChange = (event) => {
we have removed the comment. thanks!

2020-08-22 08:43 UTC, shloch approved these changes
## Hello @firmoholanda, @Cyrus-Kiprop 

![accomplished](https://user-images.githubusercontent.com/40712459/90952488-d54d6f00-e45b-11ea-9bce-ae97fc045e8d.jpg)

We're ready for next milestone....THUMBS UP

YOu can merge this

Happy coding

2020-08-22 09:51 UTC, merged